#!/usr/bin/env bash
set -e

# function
usage() {
    echo "wasi-env - Run command with WASI-SDK"
    echo ""
    echo "wasi-env is a helper to set various environment variables to"
    echo "run configure and make with WASI-SDK. A WASI-SDK must be either"
    echo "installed at /opt/wasi-sdk or the env var 'WASI_SDK_PATH' must"
    echo "set to the root of a WASI-SDK."
    echo ""
    echo "Usage: wasi-env command [...]"
    echo ""
    echo "    -h --help     display this help and exit"
    echo ""
}

case $1 in
    -h|--help)
        usage
        exit
        ;;
esac

if test -z "$1"; then
    echo "ERROR: command required" >&2
    usage
    exit 1
fi

function export_if_set_for_wasix() {
    wasix_varname="WASIX_$1"
    if [[ -v wasix_varname ]]; then
        export "$1"="${!wasix_varname}"
    fi
}

export_if_set_for_wasix LIBLZMA_CFLAGS
export_if_set_for_wasix LIBLZMA_LIBS
export_if_set_for_wasix ZLIB_CFLAGS
export_if_set_for_wasix ZLIB_LIBS
export_if_set_for_wasix LIBUUID_CFLAGS
export_if_set_for_wasix LIBUUID_LIBS
export_if_set_for_wasix LIBREADLINE_CFLAGS
export_if_set_for_wasix LIBREADLINE_LIBS
export_if_set_for_wasix CURSES_CFLAGS
export_if_set_for_wasix CURSES_LIBS
export_if_set_for_wasix PANEL_CFLAGS
export_if_set_for_wasix PANEL_LIBS
export_if_set_for_wasix LIBB2_CFLAGS
export_if_set_for_wasix LIBB2_LIBS
export_if_set_for_wasix LIBFFI_CFLAGS
export_if_set_for_wasix LIBFFI_LIBS
export_if_set_for_wasix LIBSQLITE3_CFLAGS
export_if_set_for_wasix LIBSQLITE3_LIBS

export_if_set_for_wasix PKG_CONFIG_SYSROOT_DIR
export_if_set_for_wasix PKG_CONFIG_LIBDIR

export EXTRA_CONFIGURE_FLAGS=""

# Use a compiler wrapper if available

if ! command -v wasixcc ; then
    echo "ERROR: wasixcc not found in PATH. Please install wasixcc or adjust your PATH." >&2
    exit 1
fi

export WASIXCC_FLAGS="-sPIC=yes -sWASM_EXCEPTIONS=yes -sINCLUDE_CPP_SYMBOLS=yes -sWASM_OPT_FLAGS=-O4:--strip-debug"
export RANLIB="wasixranlib"
export AR="wasixar"
export NM="wasixnm"
export CC="wasixcc $WASIXCC_FLAGS"
export CXX="wasix++ $WASIXCC_FLAGS"
export LD="wasixld"
export WASIXCC_RUN_WASM_OPT="no"
export WASIXCC_WASM_EXCEPTIONS="yes"
export WASIXCC_PIC="yes"

export CFLAGS="\
  -DOPENSSL_THREADS \
  -flto"

WASIX_PREFIX_FLAGS=
if [[ -v WASIX_INSTALL ]] ; then
    WASIX_PREFIX_FLAGS="--prefix=$WASIX_INSTALL/cpython"
elif [[ -v WASIX_PREFIX ]] ; then
    WASIX_PREFIX_FLAGS="--prefix=$WASIX_PREFIX"
fi

WASIX_OPENSSL_DIR_FLAGS=
if [[ -v WASIX_OPENSSL_DIR ]] ; then
    WASIX_OPENSSL_DIR_FLAGS="--with-openssl=$WASIX_OPENSSL_DIR"
fi

"$@" --with-readline=yes --with-ensurepip=install $WASIX_OPENSSL_DIR_FLAGS $WASIX_PREFIX_FLAGS $EXTRA_CONFIGURE_FLAGS