#!/bin/bash
set -e

# function
usage() {
    echo "wasi-env - Run command with WASI-SDK"
    echo ""
    echo "wasi-env is a helper to set various environment variables to"
    echo "run configure and make with WASI-SDK. A WASI-SDK must be either"
    echo "installed at /opt/wasi-sdk or the env var 'WASI_SDK_PATH' must"
    echo "set to the root of a WASI-SDK."
    echo ""
    echo "Usage: wasi-env command [...]"
    echo ""
    echo "    -h --help     display this help and exit"
    echo ""
}

case $1 in
    -h|--help)
        usage
        exit
        ;;
esac

if test -z "$1"; then
    echo "ERROR: command required" >&2
    usage
    exit 1
fi

export LIBLZMA_CFLAGS=$WASIX_LIBLZMA_CFLAGS
export LIBLZMA_LIBS=$WASIX_LIBLZMA_LIBS

export ZLIB_CFLAGS=$WASIX_ZLIB_CFLAGS
export ZLIB_LIBS=$WASIX_ZLIB_LIBS

export LIBUUID_CFLAGS=$WASIX_LIBUUID_CFLAGS
export LIBUUID_LIBS=$WASIX_LIBUUID_LIBS

export LIBREADLINE_CFLAGS=$WASIX_LIBREADLINE_CFLAGS
export LIBREADLINE_LIBS=$WASIX_LIBREADLINE_LIBS

export CURSES_CFLAGS=$WASIX_CURSES_CFLAGS
export CURSES_LIBS=$WASIX_CURSES_LIBS

export PANEL_CFLAGS=$WASIX_PANEL_CFLAGS
export PANEL_LIBS=$WASIX_PANEL_LIBS

export LIBB2_CFLAGS=$WASIX_LIBB2_CFLAGS
export LIBB2_LIBS=$WASIX_LIBB2_LIBS

export BZIP2_CFLAGS=$WASIX_BZIP2_CFLAGS
export BZIP2_LIBS=$WASIX_BZIP2_LIBS

export LIBFFI_CFLAGS=$WASIX_LIBFFI_CFLAGS
export LIBFFI_LIBS=$WASIX_LIBFFI_LIBS

export LIBSQLITE3_CFLAGS=$WASIX_LIBSQLITE3_CFLAGS
export LIBSQLITE3_LIBS=$WASIX_LIBSQLITE3_LIBS

export "WASIXCC_FLAGS=-sPIC=yes -sWASM_EXCEPTIONS=yes -sINCLUDE_CPP_SYMBOLS=yes -sWASM_OPT_FLAGS=-O4:--strip-debug"

export RANLIB="wasixranlib"
export AR="wasixar"
export NM="wasixnm"
export CC="wasixcc $WASIXCC_FLAGS"
export CXX="wasix++ $WASIXCC_FLAGS"
export LD="wasixld"

export CFLAGS="\
  -DOPENSSL_THREADS \
  -Os -flto"

WASIXCC_RUN_WASM_OPT=no \
  "$@" \
  --with-openssl=$WASIX_OPENSSL_DIR \
  --with-pkg-config=no \
  --with-readline=yes \
  --with-ensurepip=install \
  --prefix=$WASIX_INSTALL/cpython