#!/bin/bash
set -e

"$@"

if [ $2 != clean ]; then
    echo "Running wasm-opt..."
    # TODO: We can significantly reduce the size of the wasm file by using --strip-debug instead of -g
    wasm-opt -O4 --experimental-new-eh -g python.wasm -o python.wasm
fi

echo "Done"