#!/bin/bash
set -e

"$@"

echo "Running wasm-opt..."
# TODO: We can significantly reduce the size of the wasm file by using --strip-debug instead of -g
wasm-opt -O4 --experimental-new-eh -g python.wasm -o python.wasm

echo "Done"