[package]
name = "wasmer/python-ehpic"
version = "0.0.1"

[fs]
"/cpython" = "/tmp/wasix-install/cpython"

[[module]]
name = "python"
source = "/tmp/wasix-install/cpython/bin/python3.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "python"
module = "python"
runner = "wasi"

[command.annotations.wasi]
env = ["PYTHONEXECUTABLE=/bin/python", "PYTHONHOME=/cpython"]